### ISSUE TITLE
Spring Sleuth integration

### ISSUE THREAD

**Issue by kabennett** [spring-cloud-samples/tests#3]
Hi, Dave. I am trying to integrate Spring Sleuth into a Spring Cloud (Brixton) project I am creating, and I am just wondering if you can tell me what the status is of this project. Should I be able to integrate Spring Cloud Sleuth into the services I have developed? I am currently using Logback to log to files, and I'm wondering if this framework integrates with Logback or just what it does exactly.  I appreciate your input, and as always, I continue to be impressed with the collective work you and others at Pivotal continue to do. Thanks!

**Comment by kabennett** [comment]
Never mind, I figured out what my issue was.

**Comment by marcingrzejszczak** [comment]
You have an example of a working project with sleuth here - https://github.com/spring-cloud-samples/brewery

**Comment by kabennett** [comment]
Thanks, I will take a look.  I have the trace ID and span ID in my initial service log file, but the others that I invoke via the FeignClient don't have the trace ID and span ID in their logs.  That's what I've got to figure out next.

**Comment by marcingrzejszczak** [comment]
Feign uses Hystrix so it's spawning a new thread. We didn't manage to pass the span and trace there yet. You can disable hystrix - @spencergibb knows how to do it ;)

**Comment by spencergibb** [comment]
You can disable feign hystrix with "feign.hystrix.enabled=false".

**Comment by kabennett** [comment]
Does the road map for Spring Cloud Sleuth include passing the trace and span IDs across multiple services invoked via Feign?  Or, is the intent of Spring Cloud Sleuth to only provide those elements within a single microservice?

**Comment by spencergibb** [comment]
yes it does. spring-cloud-samples/tests is probably the wrong place to be asking these questions.

**Comment by kabennett** [comment]
Spencer, is a road map published anywhere that I can access? Also, where
should I post these types of questions?

**Comment by spencergibb** [comment]
No roadmap except github issues. https://github.com/spring-cloud/spring-cloud-sleuth
